### PR TITLE
feat: add missing automatic layout params

### LINKED ISSUE #87: Autolayout doesn't support resizePaper and margin
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/Midnighter/structurizr-python/issues) for this yet.

### Is your feature related to a problem? Please describe it.

Currently auto layout can be set with the following code:
```py
workspace.views.automatic_layout = AutomaticLayout(
            rank_direction=RankDIrection.TopBottom,
            rank_separation=300,
            edge_separation=10,
            node_separation=300,
            vertices=False
        )
```

but it only support the following parameters
```
rank_direction
rank_separation
node_separation
edge_separation
vertices
```
https://github.com/Midnighter/structurizr-python/blob/ab5adc94c188c8e4bbd05d064fce4603a22e8255/src/structurizr/view/automatic_layout.py#L32-L36

But structurizr.com supports more than that. For example resize paper
```
https://graphviz.structurizr.com/?view=id&resizePaper=true&rankDirection=TB&rankSeparation=300&nodeSeparation=300&margin=400
```

## Describe the solution you would like.
To add `resizePaper` and `margin` params support to AutomaticLayout class

## Describe alternatives you considered
Manually auto layout on structurizr.com

### PR DESCRIPTION
**Pull request by WLun001**
* [x] fix #87 
* [ ] description of feature/fix
* [ ] tests added/passed
* [x] add an entry to the [next release](../CHANGELOG.rst)

New to python, please help me to review @Midnighter

### CODE REVIEW

**Review by Midnighter — DISMISSED** [review]
I apologize for the slow response. Adding these attributes looks good to me.

**Comment by Midnighter** [comment]
Actually, I took a look at the Java and the API definition and these two attributes are not part of the `AutomaticLayout`, it seems.

**Comment by WLun001** [comment]
but i able to get it from the UI by inspecting the network tab
```
https://graphviz.structurizr.com/?view=id&resizePaper=true&rankDirection=TB&rankSeparation=300&nodeSeparation=300&margin=400
```

**Comment by Midnighter** [comment]
@simonbrowndotje can you comment on what the intention for `resizePaper` and `margin` is? From where should that be set?

**Comment by WLun001** [comment]
I found on the [java SDK](https://github.com/structurizr/java-extensions/blob/master/structurizr-graphviz/src/com/structurizr/graphviz/GraphvizAutomaticLayout.java#L51) and the [docs](https://structurizr.com/help/auto-layout)

**Comment by simonbrowndotje** [comment]
Those are only currently used when manually initiating auto-layout from the Structurizr UI.

Screenshot 2022-01-24 at 11 26 03

**Comment by Midnighter** [comment]
@WLun001 I guess this first needs to be a feature request on the Structurizr API then before we can make changes here on the Python SDK.

**Comment by WLun001** [comment]
> I found on the [java SDK](https://github.com/structurizr/java-extensions/blob/master/structurizr-graphviz/src/com/structurizr/graphviz/GraphvizAutomaticLayout.java#L51) and the [docs](https://structurizr.com/help/auto-layout)

@Midnighter how about this? already on the Java SDK

**Comment by Midnighter** [comment]
The Python package only interacts with the [web facing API](https://editor.swagger.io/?url=https://raw.githubusercontent.com/structurizr/json/master/structurizr.yaml). So we can only support what is possible through this API.

**Comment by WLun001** [comment]
@Midnighter I see. So we have to wait the web facing APIs to update

**Comment by Midnighter** [comment]
I will close this as part of a clean up.

**Pull request closed without merging**
