### PR TITLE
Implement DeploymentView

### LINKED ISSUE #55: Implement DeploymentView
### Checklist

- [X] There are [no similar issues or pull requests](https://github.com/Midnighter/structurizr-python/issues) for this yet.

### Is your feature related to a problem? Please describe it.

Following on from the main body of https://github.com/Midnighter/structurizr-python/issues/8 (Implement models, views and styles), we do not currently have an implementation for `DeploymentView`.  One consequence of this is that if you load a workspace from Structurizr into Python, do some stuff to it (e.g. add more elements or update tags/properteis) and then push it back to Structurizr, you will lose any deployment views that you had created.

## Describe the solution you would like.

Implement `DeploymentView` similarly to the other view types and uncomment those sections in the examples (with appropriate renaming of vars to be Python style).

One difficulty in implementing this (and possibly for the automated e2e tests) is that deployment views aren't available in the free licence plan.

## Additional context

From `big_bank.py`:
```python
    # DeploymentView liveDeploymentView = views.CreateDeploymentView(internet_banking_system, "LiveDeployment", "An example live deployment scenario for the Internet Banking System.")
    # liveDeploymentView.Environment = "Live"
    # liveDeploymentView.Add(big_bank_data_center)
    # liveDeploymentView.Add(customerMobileDevice)
    # liveDeploymentView.Add(customerComputer)
    # liveDeploymentView.Add(dataReplicationRelationship)
    # liveDeploymentView.PaperSize = PaperSize.A5_Landscape
```

### PR DESCRIPTION
**Pull request by yt-ms**
* [X] fix https://github.com/Midnighter/structurizr-python/issues/55
* [X] description of feature/fix
* [X] tests added/passed
* [X] add an entry to the [next release](../CHANGELOG.rst)

Add implementation of `DeploymentView`, based on the [Java equivalent](https://github.com/Midnighter/structurizr-python/issues/55).  Tests are also based on the [Java version](https://github.com/Midnighter/structurizr-python/issues/55) but with better coverage.

---------------

THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Apache License v.2.0. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://www.apache.org/licenses/LICENSE-2.0.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Review by Midnighter — CHANGES_REQUESTED** [review]
I'm not in the right mindset to go through it line-by-line at the moment but I looked over the changes in every commit and it seems very solid.

Please rebase your branch, I've added some changes to the test setup and I've added a script to the examples that let's you upload the workspace created in an example (`examples/upload_workspace.py`). Just place your credentials in a `.env` file.

When I did this for the modified Big Bank example, I get the following error from the API which we do not catch locally:

```
Traceback (most recent call last):
  File "upload_workspace.py", line 40, in <module>
    client.put_workspace(workspace)
  File "structurizr-python/src/structurizr/api/structurizr_client.py", line 189, in put_workspace
    raise StructurizrClientException(
structurizr.api.structurizr_client_exception.StructurizrClientException: Failed to update the Structurizr workspace 61189.
HTTP Status 400 - Bad Request
Error message: A deployment node named "Docker - Web Server" already exists within "Developer Laptop".
```

Can you look into that, please?

**Comment by yt-ms** [comment]
> Can you look into that, please?

Yep, will do.

**Comment by yt-ms** [comment]
OK, I think I've fixed that upload problem - it looked to be due to a bug in `DeploymentNode` where child nodes weren't picking up the environment from their parent (the error from Structurizr wasn't the most helpful).  Not related to this PR, but I've added the fix in here anyway.

**Comment by Midnighter** [comment]
Beautiful, and the graphviz-based auto-layout does a decent job: https://structurizr.com/share/61189

**Review by Midnighter — APPROVED** [review]

**Comment by yt-ms** [comment]
> Beautiful, and the graphviz-based auto-layout does a decent job: https://structurizr.com/share/61189

Nice!

**Pull request merged**
